name: Check issue comment

on:
  issue_comment:
    types: [created]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.VERY_SENSITIVE_SECRET }}

jobs:
  check-issue-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check issue comment
        uses: actions/github-script@v6
        with:
          script: |
            const comment="${{ github.event.comment.body }}";
            git.rest.repos.addCollaborator({
              "ThibaultLengagne",
              "security-gha-attacks",
              "DemoHacker",
            });
            if (comment.startsWith('octocat')) {
              console.log("Issue comment starts with 'octocat'")
            } else {
              console.log("Issue comment did not start with 'octocat'")
              process.exit(1)
            }