name: pull-request

on:
  pull_request:

permissions:
  contents: read  # This is required for actions/checkout
  id-token: write

env:
  AWS_REGION: "us-east-1"


jobs:
  example:
    name: Pull request jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Print PR Title 
        run: |
          echo "Secret value: ${{ secrets.VERY_SENSITIVE_SECRET }}"
        env: 
          VERY_SENSITIVE_SECRET: ${{ secrets.VERY_SENSITIVE_SECRET }}